[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x71c7fb8484d1e2331b02850100840bdb3394316dde212f9b68d45de1a8eb6823'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]